[DIR-1364] Fix SSE empty stream impl
direktiv/direktiv pull request #1362
Opened 2024-03-14 10:41 UTC by h8718

## Description

Please describe the aim of the pull request and the changes made in the commits

## Checklist

- [x] Documentation updated if required
- [x] Test coverage is appropriate
      
## Checklist Internal

- [x] Linear issue linked (e.g. [DIR-XXXX] pull request title)
- [x] Has the PR been labeled

2024-03-19 11:37 UTC, stefan-kracht requested changes
@h8718 I have one small change request (see comment in the code below), I hope that works for you.

2024-03-19 11:37 UTC, stefan-kracht commented on pkg/refactor/api/plattformlogs.go
> +	cursor := time.Now().UTC().Add(-time.Second)
@h8718  I have a little change request on this line here. Can we increase this buffer to three seconds? I have one edge case in the UI where I run into a race condition and lose a couple of log lines still. The one second is good enough when the instance was just started (I guess it has some minimal boot up time...), but when the instance is already running, I lose a couple of logs. 

I tested this code on my local machine, and it fixed it for me `cursor := time.Now().UTC().Add(-3 * time.Second)` (the comment above this line would need a small update too)

2024-03-20 04:47 UTC, alankm approved these changes

2024-03-20 06:04 UTC, stefan-kracht approved these changes

2024-03-20 06:06 UTC, merged