[DIR-1378] Disabling the Run Button on unsaved Changes
direktiv/direktiv pull request #1449
Opened 2024-04-15 11:46 UTC by julia-zielke

## Description

Please describe the aim of the pull request and the changes made in the commits

## Checklist

- [ ] Documentation updated if required
- [ ] Test coverage is appropriate
      
## Checklist Internal

- [ ] Linear issue linked (e.g. [DIR-XXXX] pull request title)
- [ ] Has the PR been labeled

2024-04-15 13:22 UTC, julia-zielke commented
@stefan-kracht 
Thanks again for the explanation about useContext. I feel enlightened!

I renamed everything from runable to disabled because I did not want it to be:
`<Button disabled={!runable}>`

2024-04-16 06:54 UTC, stefan-kracht requested changes
Nice. Great that you added some E2E tests as well. Made some comments below.

2024-04-16 09:09 UTC, julia-zielke commented on ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
> +    setDisabled(true);
Oh yes, thanks!

2024-04-16 09:46 UTC, stefan-kracht approved these changes
Looks 👌

2024-04-16 10:24 UTC, merged