[DIR-1644] UI support for typescript-workflows
direktiv/direktiv pull request #1655
Opened 2024-06-04 09:47 UTC by sebxian

## Description

WIP

## Checklist

- [ ] Documentation updated if required
- [ ] Test coverage is appropriate
      
## Checklist Internal

- [x] Linear issue linked (e.g. [DIR-XXXX] pull request title)
- [x] Has the PR been labeled

2024-07-22 11:53 UTC, stefan-kracht requested changes
This looks very good! I made some tiny suggestions in the code. 

In the new workflow modal, we can now end up in a state where the filename placeholder "suggests" a filename that does not comply with the workflow type. Like in the screenshot, where typescript is selected and the placeholder shows `workflow-name.yaml`. One easy way out would be to only show worklow-name.


![CleanShot 2024-07-22 at 10 54 40@2x](https://github.com/user-attachments/assets/a35dd74e-8e47-4ecd-ba32-88de59b81754)

2024-07-24 13:56 UTC, sebxian commented
> In the new workflow modal, we can now end up in a state where the filename placeholder "suggests" a filename that does not comply with the workflow type. Like in the screenshot, where typescript is selected and the placeholder shows `workflow-name.yaml`. One easy way out would be to only show worklow-name.

Good point! Fixed in c97273c93, it now generates a placeholder matching the type. Some extra logic required but I think it's good to show users the naming pattern in the placeholder instead of hiding the extension.

2024-07-24 14:32 UTC, sebxian commented on ui/src/pages/namespace/Explorer/Tree/utils.ts
> +export const addFileExtension = (name: string, extension: string) => {
done in d172be808

2024-07-24 14:37 UTC, sebxian commented on ui/src/pages/namespace/Explorer/Tree/__tests__/utils.test.ts
> +  });
I added this test case, is this what you mean?

```
  test("it does nothing if the provided extension isn't contained in the file name", () => {
    expect(subject("name.ts", "notfound")).toBe("name.ts");
  });
```

To be honest I am not sure I understand the point though.

2024-07-25 05:19 UTC, stefan-kracht commented on ui/src/pages/namespace/Explorer/Tree/__tests__/utils.test.ts
> +  });
Yes, that's what I meant. For unit tests, I like to cover as many of the possible outcomes of a function as possible, as it becomes very handy when refactoring. One possible outcome that was not covered is that this function will not change the input string at all.

2024-07-25 05:19 UTC, stefan-kracht approved these changes

2024-07-25 07:13 UTC, merged