Add interfaces for the new logging-db-logic
direktiv/direktiv pull request #861
Opened 2023-05-02 11:14 UTC by h8718

Signed-off-by: Alexander Ertli <alexander.ertli@direktiv.io>

2023-05-02 13:18 UTC, sir-hassan requested changes
I added some notes :)

2023-05-02 13:18 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +type LogQuery interface {
It's not clear how the users of LogStore would use this interface as parameter to query logs!

Can you please write an example?

2023-05-02 13:18 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +type LogQuery interface {
It's not clear how the users of LogStore would use this interface as parameter to query logs!

Can you please write an example?

2023-05-02 13:18 UTC, sir-hassan commented on pkg/util/jsonb.go
> +type JSONB map[string]interface{}
Why sql related types need to be leaked to the public here?

2023-05-02 13:18 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +func Convert(recipientType string) (RecipientType, bool) {
Why users of LogStore need to use this method?

2023-05-02 15:03 UTC, sir-hassan requested changes
I added more comments.

2023-05-02 15:03 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +	BuildStatement() (string, error)
It is not clear how this function is used by the user of LogStore?

2023-05-02 15:19 UTC, h8718 commented on pkg/refactor/logstore/logstore.go
> +	// ql := GetLogsQuery(recipienttId, recipientType, loglevel)
Its just an example how the append can be used. I can provide a example implementation of `GetLogsQuery` inside the docs, if you think we need this. 
```
func GetLogsQuery(recipienttId, recipientType, loglevel) {
    return logQ{
      recipienttId: recipienttId,
      recipientType: recipientType,
      loglevel: loglevel,
    }
}

type logQ struct {
      recipienttId recipienttId 
      recipientType recipientType,
      loglevel level,
}

func(lq logQ) BuildStatement() (string,error) {
  if recipientType xy {
      return fmt.Sprinf("SELECT from %s WHERE %s ...", lq.table,lq.recipienttId)
  }
  ...
}

2023-05-02 15:27 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +	// ql := GetLogsQuery(recipienttId, recipientType, loglevel)
@h8718 ,

This PR is about to define all the exported interfaces/types needed to make LogStore usable. Please provide all the missing types.

2023-05-02 18:05 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +	BuildStatement() (string, error)
If its intended to be used inside Get() method, why then its public and exported?

2023-05-02 21:04 UTC, sir-hassan requested changes

2023-05-02 21:04 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +	NewFilterBuilder() LogSelectorBuilder
NewFilterBuilder() Has nothing to do with the LogQuery interface. This method can be defined in the package directly.

2023-05-02 21:04 UTC, sir-hassan commented on pkg/refactor/logstore/logstore.go
> +type LogSelectorBuilder interface {
I still see that this builder doesn't work, you can verify this by writing a complete usage example.

2023-05-03 10:09 UTC, sir-hassan approved these changes
Looks nice.

2023-05-03 10:13 UTC, merged