Add tracing to the eventing
direktiv/direktiv pull request #995
Opened 2023-07-12 14:44 UTC by h8718

## Description

this PR adds basic tracing to the event processing. This is necessary to measure/validate the latency

2023-07-12 14:51 UTC, h8718 commented
@sir-hassan, @alankm if you don't have any suggestions, then this is ready to be merged.

2023-07-13 02:09 UTC, alankm requested changes

2023-07-13 02:09 UTC, alankm commented on pkg/flow/events.go
> +// TODO: this code block is dead
If this is truly dead, let's delete it.

2023-07-17 05:05 UTC, alankm approved these changes

2023-07-17 05:05 UTC, merged